### ISSUE TITLE
about flipped phase

### ISSUE THREAD

**Issue by l6chen** [yuguochencuc/BAE-Net#3]
Hi, how do you flip the LR phase in the variable bandwidth case or SR rate > 2 i.e. 8k->48k?

**Comment by yuguochencuc** [comment]
HI, usually we choose a lowest effective bandwidth to flip because we will fix the phase in pr-net, so I think there are many strategies for this part of the phase flip. In the case of 8k to 48k, I'd flip 8k to 16k and then copy it 3 times. Similarly, I've tried copying to fill 48k after flipping the phase of 8k and it also works well.

> Hi, how do you flip the LR phase in the variable bandwidth case or SR rate > 2 i.e. 8k->48k?

**Comment by yuguochencuc** [comment]
> Hi, how do you flip the LR phase in the variable bandwidth case or SR rate > 2 i.e. 8k->48k?

HI, usually we choose a lowest effective bandwidth to flip because we will fix the phase in pr-net, so I think there are many strategies for this part of the phase flip. In the case of 8k to 48k, I'd flip 8k to 16k and then copy it 3 times. Similarly, I've tried copying to fill 48k after flipping the phase of 8k and it also works well.

**Comment by l6chen** [comment]
Thanks for your explanation and your impressive work. Looking forward to your code.
